---
- name: Deploy hiTarget API
  hosts: web
  vars:
    WDIR: /var/apps/hitarget-api
    PYTHON_VERSION: pypy3.6-7.3.1
  environment:
    PYENV_ROOT: /root/.pyenv
    API_HOST: 127.0.0.1
    API_PORT: 5000
    MONGODB_NAME: hitarget
    MONGODB_URL: mongodb://10.118.0.3:27017/?authSource=admin
    MONGODB_TLS: true
    MONGODB_BYPASS_TLS: true

  tasks:
    - name: Create apps directory
      file:
        path: "{{WDIR}}"
        state: directory
        mode: 0755
    - name: Checkout branch master
      git:
        repo: git@github.com:nhtua/hitarget-api.git
        dest: "{{WDIR}}"
        depth: 1
        accept_hostkey: yes
        ssh_opts: -o StrictHostKeyChecking=no
    - name: Enable Pypy locally
      shell: "pyenv local {{PYTHON_VERSION}}"
      args:
        creates: "{{WDIR}}/.python-version"
        chdir: "{{WDIR}}"
    - name: Install dependencies
      shell: "{{ item }}"
      args:
        chdir: "{{WDIR}}"
      with_items:
        - python -m ensurepip
        - python -m pip install -U pip wheel
        - pip install poetry
        - poetry install

    - name: Start application
      shell: |
        pkill pypy3 || true
        screen -S hitarget -X quit || true
        screen -dmS hitarget
        sleep 1
        screen -S hitarget -X stuff './start.sh --workers 10 >> /var/logs/hitarget-api.log\n'
      args:
        executable: /bin/bash
        chdir: "{{ WDIR }}"
