- name: Install basic tools
  hosts: all

  tasks:
  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Install common packages
    apt:
      name:
        - git
        - curl
        - gnupg
        - ntp
        - ca-certificates
      state: present
